### ISSUE TITLE
Getting constant "Commercial pool depleted!"

### ISSUE THREAD

**Issue by ddybing** [oregonjim/leetv#3]
I am constantly getting "Commercial pool depleted! Reloading..."
I have added 8 different commercial videos (all .MP4s) of various lengths. 

When launching leetv with ./leetv -v it just spits out this error message constantly and doesn't start. 

There are no entries in used.lst. 

Any ideas what this could be caused by?

**Comment by ddybing** [comment]
Are there any naming schemes that should be avoided?

**Comment by oregonjim** [comment]
For a full day's programming, you would need at least 250-500 commercials.  That's an average of 5-10 every half hour or so, assuming "normal" commercial length of 30 seconds and "normal" program time of 20-25 minutes.

Having only 8 commercials available will cause the rollover to happen after nearly every time slot - up to 48 times in a day's programming.  By the way, this isn't an error message, just an informational one.

There are no naming restrictions beyond those of the operating system.  

If the program is not starting, check  the log file.  Chances are good that there is a syntax error in one of the schedule files that you create, or a media file cannot be found.

**Comment by ddybing** [comment]
Ah, right! Yeah, I downloaded a set of a few hundred commercials and it then ran as expected. 

Thank you very much for the quick reply and for creating this software. I am looking forward to setting up two or three TV channels to use on my retro TVs!

**Comment by oregonjim** [comment]
That's great to hear!  I'm glad it's working for you.  I will admit that the system is a bit "fiddly" to set up, but once you get it going, it practically runs itself.  I've been using it 24/7 for several years now...

**Comment by ddybing** [comment]
Since I've already got you "on the line":

Does the commercials fill inbetween series and shows as well, or does it only fill at the start/end of the given time slot? I'm aware that could be the same thing for shows that fill the majority of the slot, but I'm thinking of shows that are e.g 5 or 10 minute each.

Running this on a Pi 3B using VLC with hw/acc and it is running very nicely.

**Comment by oregonjim** [comment]
The commercials only fill the end of a time slot.  If a "show" is only 5 minutes long, then you will (potentially) get 25 minutes of commercials until the next time slot starts.  However, if you have several "episodes" of that show that are all 5 minutes long, it will fit as many episodes as possible into the time slot before resorting to commercials.  Hope that makes sense...

**Comment by ddybing** [comment]
Yep, that makes sense! Thank you very much again.
